In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Test biting scenarios

In [76]:
# Mosquito bites person with 4 infections, each of which has its own probability of transmission
strain_ids = [1,2,3,4]
infectiousness = np.array([0.001,0.01,0.05,0.1])
# infectiousness = np.array([0.1,0.1,0.1,0.1])

In [77]:
def fake_oocyst_formation(parent_strains, parent_strain_weights):
    # Choose 2 parent strains based on weights
    parent_strains = np.random.choice(parent_strains, 2, p=parent_strain_weights)

In [78]:
diversity_counter = 0
for _ in range(100000):
    # Scenario 1: Each infection is picked up independently based on its own probability of transmission
    picked_up_by_mosquito = np.random.rand(4) < infectiousness
    # print(picked_up_by_mosquito)
    strains_in_mosquito = np.array(strain_ids)[picked_up_by_mosquito]
    # print(strains_in_mosquito)
    
    if np.sum(picked_up_by_mosquito) == 0:
        # print("No infections picked up by mosquito")
        pass
    else:
        strain_weights_in_mosquito = infectiousness[picked_up_by_mosquito]/np.sum(infectiousness[picked_up_by_mosquito])
        oocyst_parents = np.random.choice(strains_in_mosquito, 2, p=strain_weights_in_mosquito)
        
        if oocyst_parents[0] != oocyst_parents[1]:
            diversity_counter += 1
            print("Diversity!")
print(diversity_counter)

Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!

In [79]:
diversity_counter = 0
for _ in range(100000):
    # Scenario 2: If any infection is picked up, all of them are picked up. 
    aggregate_infectiousness = 1-np.prod(1-infectiousness)
    picked_up_by_mosquito = np.random.rand() < aggregate_infectiousness
    
    if not picked_up_by_mosquito:
        # print("No infections picked up by mosquito")
        pass
    else:
        strains_in_mosquito = strain_ids
        strain_weights_in_mosquito = infectiousness/np.sum(infectiousness)
        oocyst_parents = np.random.choice(strains_in_mosquito, 2, p=strain_weights_in_mosquito)
        
        if oocyst_parents[0] != oocyst_parents[1]:
            diversity_counter += 1
            print("Diversity!")
print(diversity_counter)

Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!
Diversity!

In [7]:
picked_up_by_mosquito

array([False, False, False,  True])

In [10]:
np.random.choice([1,2,3,4], 2, p=infectiousness/np.sum(infectiousness))

array([4, 4])

In [82]:
# Assume that the mosquito did get infected by at least one of the strains. Then go back and pick the strains based on their weights
aggregate_infectiousness = 1-np.prod(1-infectiousness)
prob_infection_conditional_on_success = infectiousness/aggregate_infectiousness

In [83]:
prob_infection_conditional_on_success

array([0.00647683, 0.06476833, 0.32384164, 0.64768329])

In [84]:
aggregate_infectiousness

0.15439645000000013